### ISSUE TITLE
Manual horn (client)

### ISSUE THREAD

**Issue by tobire** [Shot-Clock-DLaxV/shotclock-web-client#10]
Request from TJ@WorldLacrosse:
> Manual horn – this is particularly useful at end of quarters or at end of time outs to signal play should be resuming.

Linked to https://github.com/Shot-Clock-DLaxV/shotclock-web-server/issues/4

**Comment by ChangeD20** [comment]
to be integrated in a hidden area for advanced operations (getting visible by pushing a button underneath the control button
